name: crud_object_box
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  #OBJECT_BOX
  objectbox: ^1.7.0
  objectbox_flutter_libs: any

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #OBJECT_BOX
  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0

#OBJECT_BOX
objectbox:
  output_dir: database

flutter:


  uses-material-design: true

